# Generated by Django 4.1 on 2022-10-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('jefeCalidad1', models.CharField(max_length=150)),
                ('jefeCalidad2', models.CharField(max_length=150)),
                ('jefeCalidad3', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefeLinea1', models.CharField(max_length=150)),
                ('jefeLinea2', models.CharField(max_length=150)),
                ('jefeLinea3', models.CharField(max_length=150)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas.area')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pruebaCalidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedente', models.CharField(max_length=150)),
                ('jefeLinea', models.CharField(max_length=150)),
                ('noPiezas', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas.lineaproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='lineaproduccion',
            name='procudto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas.producto'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField(auto_now=True)),
                ('horasExtra', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas.area')),
            ],
        ),
    ]
