# Generated by Django 4.1 on 2022-10-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaproduccion',
            old_name='procudto',
            new_name='producto',
        ),
    ]
