# Generated by Django 4.1 on 2022-10-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0003_alter_empleado_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
