# Generated by Django 4.1 on 2022-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0006_producto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pruebaCalidad',
            field=models.BooleanField(),
        ),
    ]
