# Generated by Django 4.1 on 2022-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0007_alter_producto_pruebacalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
