# Generated by Django 4.1 on 2022-10-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0008_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
