# Generated by Django 4.1 on 2022-09-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fechaNacimiento', models.DateField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
        ),
    ]
